package:
  name: dolang
  version: "0.0.2"

source:
  path: ../
#  git_url: https://github.com/econforge/Dolang
#  git_tag: v0.0.2

build:
  script: python setup.py install --single-version-externally-managed  --record=record.txt
  noarch_python: True
  preserve_egg_dir: True

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - numba
    - numpy
    - numexpr
    - yaml
    - nose
    - sympy
    - pip

  run:
    - python
    - numba
    - numpy
    - numexpr
    - yaml
    - nose
    - sympy

test:
  # Python imports
  imports:
    - dolang

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/econforge/Dolang
  license: BSD-2
  summary: 'Dolo modeling language'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
